appname:  "DancerDemo"
layout:   "main"
charset:  "UTF-8"
logger:   "console"
log:      "error"
template: "template_toolkit"

engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'

plugins:
    Database:
        driver:   'SQLite'
        database: 'hello.db'
